### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by stebogit** [leonardfischer/wunderground-api#1]
Hey @leonardfischer nice work here, very clean.
Would you mind if I added some test? I could send a PR for you to take a look.
I might also implement the fluid method you wanted to add.
Thanks

**Comment by leonardfischer** [comment]
Hey @stebogit that would be very nice! I haven't had a lot of time to work on this project in the past... I'd also like to create feature-specific classes to enable autocompletion!

**Comment by leonardfischer** [comment]
Everything seems to work just fine! I committed your PR a few minutes ago - thanks again for your help!

**Comment by stebogit** [comment]
sure, thanks for your work!
it was very instructive reading your neat code (in fact I got the inspiration for a similar project of mine) and play with the tests I created
