### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by shayneoneill** [leonardfischer/wunderground-api#3]
I've tried with my api key and everythng just seems to error out.  Extracting the generated URLs seem to lead to dead api end points.

Can anyone confirm that this still works?

**Comment by leonardfischer** [comment]
Hi @shayneoneill

that's a good question... Weather Underground changed it's API some time ago and (to my knowledge) has no free access anymore, so I can not really validate the functionality right now :( Or is it still possible to get access to their API? In that case I could update the library, like I updated https://github.com/leonardfischer/open-weather-map-api

**Comment by StarvingDeveloper** [comment]
> Can anyone confirm that this still works?
this is outdated and do not work.

**Comment by leonardfischer** [comment]
Hey @StarvingDeveloper thanks for the update - I will archive this repo :)
